### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

### ISSUE THREAD

**Issue by firov** [CassetteRocks/react-infinite-scroller#224]
**Describe the bug**
When scrolling browser spams to console:
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>
 - OS: MACOS
 - Browser Yandex Browser  (Chromium)
 - Version 19.6.0.1583

**Comment by Sarfarazsajjad** [comment]
I am facing the same issue, is there any solution to this ?

**Comment by chanp-ark** [comment]
I am also facing this issue, but only when scrolling down for phone media screens

**Comment by chanp-ark** [comment]
this is resolved in [`1.2.4`](https://github.com/danbovey/react-infinite-scroller/releases/tag/1.2.4)

**Comment by Haixiang6123** [comment]
@firov The updated codes is here:

```js
  mousewheelListener(e) {
    // Prevents Chrome hangups
    // See: https://stackoverflow.com/questions/47524205/random-high-content-download-time-in-chrome/47684257#47684257
    if (e.deltaY === 1 && !this.isPassiveSupported()) {
      e.preventDefault();
    }
  }
```

@chanp-ark I have read the Stackoverflow post, and have a question: The passive listener is supported in Chrome browser. So `this.isPassiveSupported()` will always return true in the Chrome browser. Then `e.preventDefault()` won't be executed in Chrome? So the "Random Hight Content Download" still happen in Chrome? (Because the post said only using `e.preventDefault()` in mousewheel listener will solve the problem).
